# Pre-commit configuration for Dynatrace MCP Server
# See https://pre-commit.com for more information

repos:
  # Code formatting with Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: Format code with Prettier
        entry: prettier --write
        language: node
        files: \.(js|jsx|ts|tsx|json|yaml|yml|md)$
        args: ['--config', '.prettierrc', '--ignore-path', '.prettierignore']

  # TypeScript compilation check
  - repo: local
    hooks:
      - id: typescript-check
        name: TypeScript compilation check
        entry: npx tsc --noEmit
        language: system
        types: [typescript]
        pass_filenames: false

  # Run unit tests
  - repo: local
    hooks:
      - id: unit-tests
        name: Run unit tests
        entry: npm run test:unit
        language: system
        pass_filenames: false
        stages: [commit]

  # Build verification
  - repo: local
    hooks:
      - id: build-check
        name: Verify build succeeds
        entry: npm run build
        language: system
        pass_filenames: false
        stages: [commit]

  # Lint package.json
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
        name: Check JSON files
        files: \.(json)$
      - id: check-yaml
        name: Check YAML files
        files: \.(yaml|yml)$
      - id: end-of-file-fixer
        name: Fix end of files
        exclude: \.min\.(js|css)$
      - id: trailing-whitespace
        name: Trim trailing whitespace
        exclude: \.min\.(js|css)$

  # Security checks
  - repo: local
    hooks:
      - id: audit-check
        name: npm audit check
        entry: npm audit --audit-level=moderate
        language: system
        pass_filenames: false
        stages: [commit]

  # Check for secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        name: Detect secrets
        exclude: \.env\.template$|\.env\.example$
        args: ['--baseline', '.secrets.baseline']

# Configuration for specific hooks
default_stages: [commit]
fail_fast: false

# Skip hooks for specific scenarios
exclude: |
  (?x)^(
    dist/.*|
    node_modules/.*|
    \.git/.*|
    .*\.min\.(js|css)$
  )$
