version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:4
    command: jekyll serve --watch --force_polling --host 0.0.0.0 --port 4000
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
