name: 'OpenTelemetry Step Wrapper'
description: 'Wrap a step with OpenTelemetry span and log capture'
inputs:
  step-name:
    description: 'Name of the step'
    required: true
  command:
    description: 'Command to execute'
    required: true
  working-directory:
    description: 'Working directory for the command'
    required: false
    default: '.'
  dynatrace-log-url:
    description: 'Dynatrace log ingest URL'
    required: false
    default: ''
  dynatrace-api-token:
    description: 'Dynatrace API token'
    required: false
    default: ''
outputs:
  exit-code:
    description: 'Exit code of the command'
    value: ${{ steps.execute.outputs.exit-code }}
  duration:
    description: 'Duration of the step in milliseconds'
    value: ${{ steps.execute.outputs.duration }}

runs:
  using: 'composite'
  steps:
    - name: Execute step with tracing and logging
      id: execute
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Generate span ID for this step
        SPAN_ID=$(openssl rand -hex 8)
        START_TIME_NS=$(($(date +%s) * 1000000000))
        START_TIMESTAMP=$(date +%s%N)
        
        echo "🔄 Starting step: ${{ inputs.step-name }}"
        echo "📋 Span ID: $SPAN_ID"
        echo "🏗️ Build type: $BUILD_TYPE"
        echo "🔗 Trace ID: $GITHUB_TRACE_ID"
        
        # Create log file for capturing command output
        LOG_FILE="/tmp/step_${{ inputs.step-name }}_$(date +%s).log"
        
        # Send initial log about step starting (this works)
        if [ -n "${{ inputs.dynatrace-log-url }}" ] && [ -n "${{ inputs.dynatrace-api-token }}" ]; then
          START_LOG="Starting step: ${{ inputs.step-name }} in workflow ${{ github.workflow }}"
          echo "$START_LOG" | tee -a "$LOG_FILE"
          
          LOG_TIMESTAMP=$(date +%s%3N)
          START_LOG_PAYLOAD=$(cat << EOF
          [{
            "content": "$START_LOG",
            "timestamp": $LOG_TIMESTAMP,
            "level": "INFO",
            "service": "dynatrace-mcp-server-build",
            "trace_id": "$GITHUB_TRACE_ID",
            "span_id": "$SPAN_ID",
            "github.workflow": "${{ github.workflow }}",
            "github.job": "${{ github.job }}",
            "github.step": "${{ inputs.step-name }}",
            "github.run_id": "${{ github.run_id }}",
            "github.actor": "${{ github.actor }}",
            "github.ref": "${{ github.ref }}",
            "build.type": "$BUILD_TYPE",
            "branch.name": "${{ github.ref_name }}",
            "ci.provider": "github-actions",
            "project.name": "dynatrace-mcp-server",
            "log.type": "step.start"
          }]
        EOF
          )
          
          curl -s -X POST "${{ inputs.dynatrace-log-url }}" \
            -H "Authorization: Api-Token ${{ inputs.dynatrace-api-token }}" \
            -H "Content-Type: application/json" \
            -d "$START_LOG_PAYLOAD" > /dev/null 2>&1 || true
        fi
        
        # Send start span trace using proper OTel Node.js approach
        echo "📡 Sending start span trace using OTel Node.js..."
        cd /tmp
        export NODE_PATH="/tmp/node_modules:$NODE_PATH"
        export GITHUB_WORKFLOW="${{ github.workflow }}"
        export GITHUB_JOB="${{ github.job }}"
        export GITHUB_RUN_ID="${{ github.run_id }}"
        export GITHUB_ACTOR="${{ github.actor }}"
        export GITHUB_REF="${{ github.ref }}"
        
        node send-trace.js \
          "$OTEL_EXPORTER_OTLP_ENDPOINT" \
          "$DYNATRACE_API_TOKEN" \
          "dynatrace-mcp-server-build" \
          "step-${{ inputs.step-name }}" \
          '{"step.name":"${{ inputs.step-name }}","build.type":"'$BUILD_TYPE'"}' || echo "⚠️ Start trace failed"
        
        # Return to working directory
        cd "${{ inputs.working-directory }}"
        
        # Execute command with output capture
        set +e
        ${{ inputs.command }} 2>&1 | tee -a "$LOG_FILE"
        EXIT_CODE=${PIPESTATUS[0]}
        set -e
        
        # Calculate duration
        END_TIME_NS=$(($(date +%s) * 1000000000))
        END_TIMESTAMP=$(date +%s%N)
        DURATION=$(( (END_TIMESTAMP - START_TIMESTAMP) / 1000000 ))
        
        # Determine status
        if [ $EXIT_CODE -eq 0 ]; then
          LOG_LEVEL="INFO"
          echo "✅ Step completed successfully (build: $BUILD_TYPE)"
        else
          LOG_LEVEL="ERROR"
          echo "❌ Step failed with exit code: $EXIT_CODE (build: $BUILD_TYPE)"
        fi
        
        # Send completion span trace using proper OTel Node.js approach
        echo "📡 Sending completion span trace using OTel Node.js..."
        cd /tmp
        export NODE_PATH="/tmp/node_modules:$NODE_PATH"
        
        node send-trace.js \
          "$OTEL_EXPORTER_OTLP_ENDPOINT" \
          "$DYNATRACE_API_TOKEN" \
          "dynatrace-mcp-server-build" \
          "step-${{ inputs.step-name }}-complete" \
          '{"step.name":"${{ inputs.step-name }}","step.exit_code":'$EXIT_CODE',"step.duration_ms":'$DURATION',"build.type":"'$BUILD_TYPE'"}' || echo "⚠️ Completion trace failed"
        
        # Return to working directory
        cd "${{ inputs.working-directory }}"
        
        # Send command output logs to Dynatrace (this works)
        if [ -n "${{ inputs.dynatrace-log-url }}" ] && [ -n "${{ inputs.dynatrace-api-token }}" ] && [ -f "$LOG_FILE" ]; then
          LOG_CONTENT=$(cat "$LOG_FILE" | jq -Rs .)
          LOG_TIMESTAMP=$(date +%s%3N)
          
          FINAL_LOG_PAYLOAD=$(cat << EOF
          [{
            "content": $LOG_CONTENT,
            "timestamp": $LOG_TIMESTAMP,
            "level": "$LOG_LEVEL",
            "service": "dynatrace-mcp-server-build",
            "trace_id": "$GITHUB_TRACE_ID",
            "span_id": "$SPAN_ID",
            "github.workflow": "${{ github.workflow }}",
            "github.job": "${{ github.job }}",
            "github.step": "${{ inputs.step-name }}",
            "github.run_id": "${{ github.run_id }}",
            "github.actor": "${{ github.actor }}",
            "github.ref": "${{ github.ref }}",
            "build.type": "$BUILD_TYPE",
            "branch.name": "${{ github.ref_name }}",
            "ci.provider": "github-actions",
            "project.name": "dynatrace-mcp-server",
            "step.exit_code": "$EXIT_CODE",
            "step.duration_ms": "$DURATION",
            "log.type": "step.output"
          }]
        EOF
          )
          
          curl -s -X POST "${{ inputs.dynatrace-log-url }}" \
            -H "Authorization: Api-Token ${{ inputs.dynatrace-api-token }}" \
            -H "Content-Type: application/json" \
            -d "$FINAL_LOG_PAYLOAD" > /dev/null 2>&1 || true
          
          echo "📝 Step output sent to Dynatrace logs"
          rm -f "$LOG_FILE"
        fi
        
        # Set outputs
        echo "exit-code=$EXIT_CODE" >> $GITHUB_OUTPUT
        echo "duration=$DURATION" >> $GITHUB_OUTPUT
        
        # Preserve exit code for workflow
        exit $EXIT_CODE
              "scopeSpans": [
                {
                  "scope": {
                    "name": "github-actions-otel",
                    "version": "1.0.0"
                  },
                  "spans": [
                    {
                      "traceId": "$GITHUB_TRACE_ID",
                      "spanId": "$SPAN_ID",
                      "parentSpanId": "$GITHUB_JOB_SPAN_ID",
                      "name": "step-${{ inputs.step-name }}",
                      "kind": 3,
                      "startTimeUnixNano": "$START_TIME_NS",
                      "endTimeUnixNano": "$END_TIME_NS",
                      "status": {
                        "code": $SPAN_STATUS_CODE
                      },
                      "attributes": [
                        {
                          "key": "step.name",
                          "value": {
                            "stringValue": "${{ inputs.step-name }}"
                          }
                        },
                        {
                          "key": "step.exit_code", 
                          "value": {
                            "intValue": $EXIT_CODE
                          }
                        },
                        {
                          "key": "step.duration_ms",
                          "value": {
                            "intValue": $DURATION
                          }
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
        EOF
        )
        
        echo "📡 Sending completion span trace..."
        send-trace "$OTEL_EXPORTER_OTLP_ENDPOINT" "$DYNATRACE_API_TOKEN" "$COMPLETION_TRACE_PAYLOAD" || echo "⚠️ Completion trace failed"
        
        # Send command output logs to Dynatrace (this works)
        if [ -n "${{ inputs.dynatrace-log-url }}" ] && [ -n "${{ inputs.dynatrace-api-token }}" ] && [ -f "$LOG_FILE" ]; then
          LOG_CONTENT=$(cat "$LOG_FILE" | jq -Rs .)
          LOG_TIMESTAMP=$(date +%s%3N)
          
          FINAL_LOG_PAYLOAD=$(cat << EOF
          [{
            "content": $LOG_CONTENT,
            "timestamp": $LOG_TIMESTAMP,
            "level": "$LOG_LEVEL",
            "service": "dynatrace-mcp-server-build",
            "trace_id": "$GITHUB_TRACE_ID",
            "span_id": "$SPAN_ID",
            "github.workflow": "${{ github.workflow }}",
            "github.job": "${{ github.job }}",
            "github.step": "${{ inputs.step-name }}",
            "github.run_id": "${{ github.run_id }}",
            "github.actor": "${{ github.actor }}",
            "github.ref": "${{ github.ref }}",
            "build.type": "$BUILD_TYPE",
            "branch.name": "${{ github.ref_name }}",
            "ci.provider": "github-actions",
            "project.name": "dynatrace-mcp-server",
            "step.exit_code": "$EXIT_CODE",
            "step.duration_ms": "$DURATION",
            "log.type": "step.output"
          }]
        EOF
          )
          
          curl -s -X POST "${{ inputs.dynatrace-log-url }}" \
            -H "Authorization: Api-Token ${{ inputs.dynatrace-api-token }}" \
            -H "Content-Type: application/json" \
            -d "$FINAL_LOG_PAYLOAD" > /dev/null 2>&1 || true
          
          echo "📝 Step output sent to Dynatrace logs"
          rm -f "$LOG_FILE"
        fi
        
        # Set outputs
        echo "exit-code=$EXIT_CODE" >> $GITHUB_OUTPUT
        echo "duration=$DURATION" >> $GITHUB_OUTPUT
        
        # Preserve exit code for workflow
        exit $EXIT_CODE
