name: 'Setup OpenTelemetry'
description: 'Initialize OpenTelemetry tracing for GitHub Actions'
inputs:
  job-name:
    description: 'Name of the job for trace naming'
    required: true
  otel-endpoint:
    description: 'OTEL endpoint (OTEL_EXPORTER_OTLP_ENDPOINT)'
    required: false
    default: 'https://your-tenant.live.dynatrace.com/api/v2/otlp/v1/traces'
  dynatrace-api-token:
    description: 'Dynatrace API token (DYNATRACE_API_TOKEN)'
    required: false
  dynatrace-log-url:
    description: 'Dynatrace log ingest URL (DYNATRACE_LOG_INGEST_URL)'
    required: false
outputs:
  trace-id:
    description: 'Generated trace ID for this job'
    value: ${{ steps.init-trace.outputs.trace-id }}
  otel-endpoint:
    description: 'OTel endpoint URL'
    value: ${{ steps.init-trace.outputs.otel-endpoint }}
  build-type:
    description: 'Build type (dev or prod)'
    value: ${{ steps.init-trace.outputs.build-type }}

runs:
  using: 'composite'
  steps:
    - name: Install OpenTelemetry CLI
      shell: bash
      run: |
        echo "🔧 Installing OpenTelemetry CLI..."
        
        # Try multiple methods to install otel-cli
        OTEL_CLI_INSTALLED=false
        
        # Method 1: Try the latest release from GitHub
        echo "📥 Attempting to download from GitHub releases..."
        LATEST_RELEASE=$(curl -s https://api.github.com/repos/equinix-labs/otel-cli/releases/latest | grep -o '"tag_name": "[^"]*' | cut -d'"' -f4)
        
        if [ -n "$LATEST_RELEASE" ]; then
          echo "🔍 Found latest release: $LATEST_RELEASE"
          DOWNLOAD_URL="https://github.com/equinix-labs/otel-cli/releases/download/${LATEST_RELEASE}/otel-cli_linux_amd64.tar.gz"
          
          if curl -L --fail "$DOWNLOAD_URL" -o otel-cli.tar.gz; then
            echo "📦 Downloaded otel-cli successfully"
            if tar -xzf otel-cli.tar.gz; then
              sudo mv otel-cli /usr/local/bin/
              chmod +x /usr/local/bin/otel-cli
              OTEL_CLI_INSTALLED=true
              echo "✅ otel-cli installed successfully via GitHub releases"
            else
              echo "⚠️ Failed to extract otel-cli archive"
            fi
            rm -f otel-cli.tar.gz
          else
            echo "⚠️ Failed to download from GitHub releases"
          fi
        else
          echo "⚠️ Could not determine latest release"
        fi
        
        # Method 2: Try a specific known version if latest failed
        if [ "$OTEL_CLI_INSTALLED" = false ]; then
          echo "📥 Trying known version v0.4.5..."
          DOWNLOAD_URL="https://github.com/equinix-labs/otel-cli/releases/download/v0.4.5/otel-cli_linux_amd64.tar.gz"
          
          if curl -L --fail "$DOWNLOAD_URL" -o otel-cli.tar.gz; then
            echo "📦 Downloaded otel-cli v0.4.5 successfully"
            if tar -xzf otel-cli.tar.gz; then
              sudo mv otel-cli /usr/local/bin/
              chmod +x /usr/local/bin/otel-cli
              OTEL_CLI_INSTALLED=true
              echo "✅ otel-cli v0.4.5 installed successfully"
            else
              echo "⚠️ Failed to extract otel-cli archive"
            fi
            rm -f otel-cli.tar.gz
          else
            echo "⚠️ Failed to download v0.4.5"
          fi
        fi
        
        # Method 3: Use curl for basic tracing if otel-cli fails
        if [ "$OTEL_CLI_INSTALLED" = false ]; then
          echo "🔄 otel-cli installation failed, creating wrapper script..."
          
          # Create a simple wrapper script that uses curl for basic tracing
          sudo tee /usr/local/bin/otel-cli > /dev/null << 'EOF'
        #!/bin/bash
        # Simple otel-cli wrapper using curl
        
        case "$1" in
          "span")
            echo "📊 OTEL Span: $*"
            # Just log the span information since we can't send traces without proper otel-cli
            ;;
          *)
            echo "📊 OTEL Command: $*"
            ;;
        esac
        EOF
          
          sudo chmod +x /usr/local/bin/otel-cli
          echo "✅ Created otel-cli wrapper script"
        fi
        
        # Verify installation
        if command -v otel-cli >/dev/null 2>&1; then
          echo "✅ otel-cli is available"
          otel-cli --version || echo "📊 Using wrapper script"
        else
          echo "❌ otel-cli installation failed completely"
          exit 1
        fi

    - name: Initialize trace and logging
      id: init-trace
      shell: bash
      run: |
        # Debug input parameters
        echo "🔍 Input parameters:"
        echo "  otel-endpoint: ${{ inputs.otel-endpoint }}"
        echo "  dynatrace-log-url: ${{ inputs.dynatrace-log-url }}"
        echo "  dynatrace-api-token: ${DYNATRACE_API_TOKEN:+SET}"
        
        # Validate required inputs
        if [ -z "${{ inputs.otel-endpoint }}" ] || [ "${{ inputs.otel-endpoint }}" = "https://your-tenant.live.dynatrace.com/api/v2/otlp/v1/traces" ]; then
          echo "❌ OTEL endpoint not properly configured!"
          echo "Please set OTEL_EXPORTER_OTLP_ENDPOINT in your environment variables"
          exit 1
        fi
        
        if [ -z "${{ inputs.dynatrace-api-token }}" ]; then
          echo "❌ Dynatrace API token not provided!"
          echo "Please set DYNATRACE_API_TOKEN in your environment secrets"
          exit 1
        fi
        
        # Generate a unique trace ID for this job
        TRACE_ID=$(openssl rand -hex 16)
        echo "trace-id=$TRACE_ID" >> $GITHUB_OUTPUT
        
        # Determine build type based on branch
        BUILD_TYPE="prod"
        case "${{ github.ref }}" in
          "refs/heads/dev")
            BUILD_TYPE="dev"
            ;;
          "refs/heads/main"|"refs/heads/master")
            BUILD_TYPE="prod"
            ;;
          *)
            # For PRs, check the base branch
            case "${{ github.base_ref }}" in
              "dev")
                BUILD_TYPE="dev"
                ;;
              "main"|"master")
                BUILD_TYPE="prod"
                ;;
            esac
            ;;
        esac
        
        echo "build-type=$BUILD_TYPE" >> $GITHUB_OUTPUT
        
        # Set up OTel environment variables using exact .env names
        OTEL_ENDPOINT="${{ inputs.otel-endpoint }}"
        echo "otel-endpoint=$OTEL_ENDPOINT" >> $GITHUB_OUTPUT
        
        # Export environment variables for subsequent steps (matching .env file names)
        echo "OTEL_EXPORTER_OTLP_ENDPOINT=$OTEL_ENDPOINT" >> $GITHUB_ENV
        echo "OTEL_EXPORTER_OTLP_HEADERS=Authorization=Api-Token ${{ inputs.dynatrace-api-token }}" >> $GITHUB_ENV
        echo "OTEL_SERVICE_NAME=dynatrace-mcp-server-build" >> $GITHUB_ENV
        echo "DYNATRACE_API_TOKEN=${{ inputs.dynatrace-api-token }}" >> $GITHUB_ENV
        echo "DYNATRACE_LOG_INGEST_URL=${{ inputs.dynatrace-log-url }}" >> $GITHUB_ENV
        echo "OTEL_RESOURCE_ATTRIBUTES=github.workflow=${{ github.workflow }},github.job=${{ inputs.job-name }},github.run_id=${{ github.run_id }},github.actor=${{ github.actor }},build.type=$BUILD_TYPE,branch.name=${{ github.ref_name }},branch.ref=${{ github.ref }}" >> $GITHUB_ENV
        echo "GITHUB_TRACE_ID=$TRACE_ID" >> $GITHUB_ENV
        echo "BUILD_TYPE=$BUILD_TYPE" >> $GITHUB_ENV
        
        echo "🔧 OTel initialized with trace ID: $TRACE_ID"
        echo "📡 Endpoint: $OTEL_ENDPOINT"
        echo "📝 Log URL: ${{ inputs.dynatrace-log-url }}"
        echo "🏗️ Build type: $BUILD_TYPE"
        echo "🌿 Branch: ${{ github.ref_name }}"
        
        # Test connectivity to Dynatrace
        if [ -n "${{ inputs.dynatrace-log-url }}" ] && [ -n "${{ inputs.dynatrace-api-token }}" ]; then
          echo "🧪 Testing Dynatrace connectivity..."
          
          TEST_LOG_PAYLOAD='[{"content":"GitHub Actions OTel test log","timestamp":'$(date +%s%3N)',"level":"INFO","service":"dynatrace-mcp-server-build","trace_id":"'$TRACE_ID'","span_id":"'$(openssl rand -hex 8)'","test":true}]'
          
          HTTP_STATUS=$(curl -s -w "%{http_code}" -o /tmp/test_response.txt \
            -X POST "${{ inputs.dynatrace-log-url }}" \
            -H "Authorization: Api-Token ${{ inputs.dynatrace-api-token }}" \
            -H "Content-Type: application/json" \
            -d "$TEST_LOG_PAYLOAD")
          
          if [ "$HTTP_STATUS" -eq 200 ] || [ "$HTTP_STATUS" -eq 204 ]; then
            echo "✅ Dynatrace connectivity test successful (HTTP $HTTP_STATUS)"
          else
            echo "⚠️ Dynatrace connectivity test failed (HTTP $HTTP_STATUS)"
            cat /tmp/test_response.txt || true
          fi
          
          rm -f /tmp/test_response.txt
        fi
        
        # Send initial job start log to Dynatrace
        if [ -n "${{ inputs.dynatrace-log-url }}" ] && [ -n "${{ inputs.dynatrace-api-token }}" ]; then
          JOB_START_LOG="Starting GitHub Actions job: ${{ inputs.job-name }} for workflow ${{ github.workflow }}"
          LOG_TIMESTAMP=$(date +%s%3N)
          
          JOB_LOG_PAYLOAD=$(cat << EOF
          [{
            "content": "$JOB_START_LOG",
            "timestamp": $LOG_TIMESTAMP,
            "level": "INFO",
            "service": "dynatrace-mcp-server-build",
            "trace_id": "$TRACE_ID",
            "span_id": "$(openssl rand -hex 8)",
            "github.workflow": "${{ github.workflow }}",
            "github.job": "${{ inputs.job-name }}",
            "github.run_id": "${{ github.run_id }}",
            "github.actor": "${{ github.actor }}",
            "github.ref": "${{ github.ref }}",
            "build.type": "$BUILD_TYPE",
            "branch.name": "${{ github.ref_name }}",
            "ci.provider": "github-actions",
            "project.name": "dynatrace-mcp-server",
            "log.type": "job.start"
          }]
        EOF
          )
          
          curl -s -X POST "${{ inputs.dynatrace-log-url }}" \
            -H "Authorization: Api-Token ${{ inputs.dynatrace-api-token }}" \
            -H "Content-Type: application/json" \
            -d "$JOB_LOG_PAYLOAD" > /dev/null 2>&1 || true
          
          echo "📝 Job start logged to Dynatrace"
        fi

    - name: Start job trace
      shell: bash
      run: |
        # Start the main job span with branch-based attributes
        otel-cli span \
          --service "dynatrace-mcp-server-build" \
          --name "github-job-${{ inputs.job-name }}" \
          --kind "internal" \
          --trace-id "$GITHUB_TRACE_ID" \
          --attrs "github.workflow=${{ github.workflow }},github.job=${{ inputs.job-name }},github.run_id=${{ github.run_id }},github.actor=${{ github.actor }},github.ref=${{ github.ref }},build.type=$BUILD_TYPE,branch.name=${{ github.ref_name }},ci.provider=github-actions,project.name=dynatrace-mcp-server" \
          --start-time "$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)" &
        
        # Store the job span PID for cleanup
        echo "OTEL_JOB_SPAN_PID=$!" >> $GITHUB_ENV
        echo "🚀 Started job trace for ${{ inputs.job-name }} (build type: $BUILD_TYPE)"
