name: 'Setup OpenTelemetry'
description: 'Initialize OpenTelemetry tracing for GitHub Actions'
inputs:
  job-name:
    description: 'Name of the job for trace naming'
    required: true
  otel-endpoint:
    description: 'OTEL endpoint (OTEL_EXPORTER_OTLP_ENDPOINT)'
    required: false
    default: 'https://your-tenant.live.dynatrace.com/api/v2/otlp/v1/traces'
  dynatrace-api-token:
    description: 'Dynatrace API token (DYNATRACE_API_TOKEN)'
    required: false
  dynatrace-log-url:
    description: 'Dynatrace log ingest URL (DYNATRACE_LOG_INGEST_URL)'
    required: false
outputs:
  trace-id:
    description: 'Generated trace ID for this job'
    value: ${{ steps.init-trace.outputs.trace-id }}
  otel-endpoint:
    description: 'OTel endpoint URL'
    value: ${{ steps.init-trace.outputs.otel-endpoint }}
  build-type:
    description: 'Build type (dev or prod)'
    value: ${{ steps.init-trace.outputs.build-type }}

runs:
  using: 'composite'
  steps:
    - name: Install trace sending utilities
      shell: bash
      run: |
        echo "🔧 Installing trace utilities..."
        
        # Create a trace sending function
        sudo tee /usr/local/bin/send-trace > /dev/null << 'EOF'
        #!/bin/bash
        # Direct trace sender using curl
        
        TRACE_ENDPOINT="$1"
        API_TOKEN="$2"
        TRACE_PAYLOAD="$3"
        
        if [ -z "$TRACE_ENDPOINT" ] || [ -z "$API_TOKEN" ] || [ -z "$TRACE_PAYLOAD" ]; then
          echo "❌ Missing required parameters for trace sending"
          exit 1
        fi
        
        echo "📡 Sending trace to: $TRACE_ENDPOINT"
        
        HTTP_STATUS=$(curl -s -w "%{http_code}" -o /tmp/trace_response.txt \
          -X POST "$TRACE_ENDPOINT" \
          -H "Authorization: Api-Token $API_TOKEN" \
          -H "Content-Type: application/json" \
          -d "$TRACE_PAYLOAD")
        
        echo "📊 Trace HTTP Status: $HTTP_STATUS"
        
        if [ "$HTTP_STATUS" -eq 200 ] || [ "$HTTP_STATUS" -eq 202 ] || [ "$HTTP_STATUS" -eq 204 ]; then
          echo "✅ Trace sent successfully"
        else
          echo "❌ Failed to send trace (HTTP $HTTP_STATUS)"
          echo "Response:"
          cat /tmp/trace_response.txt || true
        fi
        
        rm -f /tmp/trace_response.txt
        EOF
        
        sudo chmod +x /usr/local/bin/send-trace
        echo "✅ Trace utilities installed"

    - name: Initialize trace and logging
      id: init-trace
      shell: bash
      run: |
        # Debug input parameters
        echo "🔍 Input parameters:"
        echo "  otel-endpoint: ${{ inputs.otel-endpoint }}"
        echo "  dynatrace-log-url: ${{ inputs.dynatrace-log-url }}"
        echo "  dynatrace-api-token: ${DYNATRACE_API_TOKEN:+SET}"
        
        # Validate required inputs
        if [ -z "${{ inputs.otel-endpoint }}" ] || [ "${{ inputs.otel-endpoint }}" = "https://your-tenant.live.dynatrace.com/api/v2/otlp/v1/traces" ]; then
          echo "❌ OTEL endpoint not properly configured!"
          echo "Please set OTEL_EXPORTER_OTLP_ENDPOINT in your environment variables"
          exit 1
        fi
        
        if [ -z "${{ inputs.dynatrace-api-token }}" ]; then
          echo "❌ Dynatrace API token not provided!"
          echo "Please set DYNATRACE_API_TOKEN in your environment secrets"
          exit 1
        fi
        
        # Generate a unique trace ID for this job
        TRACE_ID=$(openssl rand -hex 16)
        echo "trace-id=$TRACE_ID" >> $GITHUB_OUTPUT
        
        # Determine build type based on branch
        BUILD_TYPE="prod"
        case "${{ github.ref }}" in
          "refs/heads/dev")
            BUILD_TYPE="dev"
            ;;
          "refs/heads/main"|"refs/heads/master")
            BUILD_TYPE="prod"
            ;;
          *)
            # For PRs, check the base branch
            case "${{ github.base_ref }}" in
              "dev")
                BUILD_TYPE="dev"
                ;;
              "main"|"master")
                BUILD_TYPE="prod"
                ;;
            esac
            ;;
        esac
        
        echo "build-type=$BUILD_TYPE" >> $GITHUB_OUTPUT
        
        # Set up OTel environment variables using exact .env names
        OTEL_ENDPOINT="${{ inputs.otel-endpoint }}"
        echo "otel-endpoint=$OTEL_ENDPOINT" >> $GITHUB_OUTPUT
        
        # Export environment variables for subsequent steps (matching .env file names)
        echo "OTEL_EXPORTER_OTLP_ENDPOINT=$OTEL_ENDPOINT" >> $GITHUB_ENV
        echo "OTEL_EXPORTER_OTLP_HEADERS=Authorization=Api-Token ${{ inputs.dynatrace-api-token }}" >> $GITHUB_ENV
        echo "OTEL_SERVICE_NAME=dynatrace-mcp-server-build" >> $GITHUB_ENV
        echo "DYNATRACE_API_TOKEN=${{ inputs.dynatrace-api-token }}" >> $GITHUB_ENV
        echo "DYNATRACE_LOG_INGEST_URL=${{ inputs.dynatrace-log-url }}" >> $GITHUB_ENV
        echo "OTEL_RESOURCE_ATTRIBUTES=github.workflow=${{ github.workflow }},github.job=${{ inputs.job-name }},github.run_id=${{ github.run_id }},github.actor=${{ github.actor }},build.type=$BUILD_TYPE,branch.name=${{ github.ref_name }},branch.ref=${{ github.ref }}" >> $GITHUB_ENV
        echo "GITHUB_TRACE_ID=$TRACE_ID" >> $GITHUB_ENV
        echo "BUILD_TYPE=$BUILD_TYPE" >> $GITHUB_ENV
        
        echo "🔧 OTel initialized with trace ID: $TRACE_ID"
        echo "📡 Endpoint: $OTEL_ENDPOINT"
        echo "📝 Log URL: ${{ inputs.dynatrace-log-url }}"
        echo "🏗️ Build type: $BUILD_TYPE"
        echo "🌿 Branch: ${{ github.ref_name }}"
        
        # Test connectivity to Dynatrace OTLP endpoint
        echo "🧪 Testing Dynatrace OTLP connectivity..."
        
        # Create a test trace payload
        CURRENT_TIME_NS=$(($(date +%s) * 1000000000))
        TEST_SPAN_ID=$(openssl rand -hex 8)
        
        TEST_TRACE_PAYLOAD=$(cat << EOF
        {
          "resourceSpans": [
            {
              "resource": {
                "attributes": [
                  {"key": "service.name", "value": {"stringValue": "dynatrace-mcp-server-build"}},
                  {"key": "github.workflow", "value": {"stringValue": "${{ github.workflow }}"}},
                  {"key": "github.job", "value": {"stringValue": "${{ inputs.job-name }}"}},
                  {"key": "build.type", "value": {"stringValue": "$BUILD_TYPE"}},
                  {"key": "test", "value": {"boolValue": true}}
                ]
              },
              "instrumentationLibrarySpans": [
                {
                  "instrumentationLibrary": {
                    "name": "github-actions-otel"
                  },
                  "spans": [
                    {
                      "traceId": "$TRACE_ID",
                      "spanId": "$TEST_SPAN_ID",
                      "name": "github-connectivity-test",
                      "kind": "SPAN_KIND_INTERNAL",
                      "startTimeUnixNano": "$CURRENT_TIME_NS",
                      "endTimeUnixNano": "$((CURRENT_TIME_NS + 1000000))",
                      "attributes": [
                        {"key": "test.type", "value": {"stringValue": "connectivity"}}
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
        EOF
        )
        
        # Send test trace
        send-trace "$OTEL_ENDPOINT" "${{ inputs.dynatrace-api-token }}" "$TEST_TRACE_PAYLOAD"
        
        # Debug output for trace sending
        echo "🔍 Test trace payload:"
        echo "$TEST_TRACE_PAYLOAD" | jq '.'
        
        # Wait for a few seconds to allow trace to be processed
        echo "⏳ Waiting for trace processing..."
        sleep 5
        
        # Check trace in Dynatrace
        echo "🔍 Checking trace in Dynatrace..."
        
        TRACE_CHECK_PAYLOAD=$(cat << EOF
        {
          "traceId": "$TRACE_ID"
        }
        EOF
        )
        
        send-trace "$OTEL_ENDPOINT" "${{ inputs.dynatrace-api-token }}" "$TRACE_CHECK_PAYLOAD"
        
        # ...existing code...

    - name: Start job trace
      shell: bash
      run: |
        echo "🚀 Starting job trace for ${{ inputs.job-name }} (build type: $BUILD_TYPE)"
        
        # Create job span payload
        CURRENT_TIME_NS=$(($(date +%s) * 1000000000))
        JOB_SPAN_ID=$(openssl rand -hex 8)
        
        JOB_TRACE_PAYLOAD=$(cat << EOF
        {
          "resourceSpans": [
            {
              "resource": {
                "attributes": [
                  {"key": "service.name", "value": {"stringValue": "dynatrace-mcp-server-build"}},
                  {"key": "github.workflow", "value": {"stringValue": "${{ github.workflow }}"}},
                  {"key": "github.job", "value": {"stringValue": "${{ inputs.job-name }}"}},
                  {"key": "github.run_id", "value": {"stringValue": "${{ github.run_id }}"}},
                  {"key": "github.actor", "value": {"stringValue": "${{ github.actor }}"}},
                  {"key": "github.ref", "value": {"stringValue": "${{ github.ref }}"}},
                  {"key": "build.type", "value": {"stringValue": "$BUILD_TYPE"}},
                  {"key": "branch.name", "value": {"stringValue": "${{ github.ref_name }}"}},
                  {"key": "ci.provider", "value": {"stringValue": "github-actions"}},
                  {"key": "project.name", "value": {"stringValue": "dynatrace-mcp-server"}}
                ]
              },
              "instrumentationLibrarySpans": [
                {
                  "instrumentationLibrary": {
                    "name": "github-actions-otel"
                  },
                  "spans": [
                    {
                      "traceId": "$GITHUB_TRACE_ID",
                      "spanId": "$JOB_SPAN_ID",
                      "name": "github-job-${{ inputs.job-name }}",
                      "kind": "SPAN_KIND_INTERNAL",
                      "startTimeUnixNano": "$CURRENT_TIME_NS",
                      "attributes": [
                        {"key": "job.name", "value": {"stringValue": "${{ inputs.job-name }}"}}
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
        EOF
        )
        
        # Send job trace
        send-trace "$OTEL_EXPORTER_OTLP_ENDPOINT" "$DYNATRACE_API_TOKEN" "$JOB_TRACE_PAYLOAD"
        
        # Store job span info for later completion
        echo "GITHUB_JOB_SPAN_ID=$JOB_SPAN_ID" >> $GITHUB_ENV
        echo "GITHUB_JOB_START_TIME_NS=$CURRENT_TIME_NS" >> $GITHUB_ENV
