name: 'Setup OpenTelemetry'
description: 'Initialize OpenTelemetry tracing for GitHub Actions'
inputs:
  job-name:
    description: 'Name of the job for trace naming'
    required: true
  otel-endpoint:
    description: 'OTEL endpoint (OTEL_EXPORTER_OTLP_ENDPOINT)'
    required: false
    default: 'https://your-tenant.live.dynatrace.com/api/v2/otlp/v1/traces'
  dynatrace-api-token:
    description: 'Dynatrace API token (DYNATRACE_API_TOKEN)'
    required: false
  dynatrace-log-url:
    description: 'Dynatrace log ingest URL (DYNATRACE_LOG_INGEST_URL)'
    required: false
outputs:
  trace-id:
    description: 'Generated trace ID for this job'
    value: ${{ steps.init-trace.outputs.trace-id }}
  otel-endpoint:
    description: 'OTel endpoint URL'
    value: ${{ steps.init-trace.outputs.otel-endpoint }}
  build-type:
    description: 'Build type (dev or prod)'
    value: ${{ steps.init-trace.outputs.build-type }}

runs:
  using: 'composite'
  steps:
    - name: Install trace sending utilities
      shell: bash
      run: |
        echo "🔧 Installing trace utilities..."
        
        # Install required tools
        sudo apt-get update
        sudo apt-get install -y jq curl
        
        # Create a comprehensive trace sending function
        sudo tee /usr/local/bin/send-trace > /dev/null << 'EOF'
        #!/bin/bash
        # Direct trace sender with OTLP JSON format
        
        TRACE_ENDPOINT="$1"
        API_TOKEN="$2"
        TRACE_PAYLOAD="$3"
        
        if [ -z "$TRACE_ENDPOINT" ] || [ -z "$API_TOKEN" ] || [ -z "$TRACE_PAYLOAD" ]; then
          echo "❌ Missing required parameters for trace sending"
          exit 1
        fi
        
        echo "📡 Sending trace to: $TRACE_ENDPOINT"
        echo "🔍 Payload preview: $(echo "$TRACE_PAYLOAD" | head -c 200)..."
        
        # Method 1: Try JSON OTLP endpoint with correct content type
        JSON_ENDPOINT="${TRACE_ENDPOINT/\/v1\/traces/\/v1\/traces}"
        echo "🔄 Method 1: JSON OTLP endpoint"
        HTTP_STATUS=$(curl -s -w "%{http_code}" -o /tmp/trace_response1.txt \
          -X POST "$JSON_ENDPOINT" \
          -H "Authorization: Api-Token $API_TOKEN" \
          -H "Content-Type: application/json" \
          -H "User-Agent: opentelemetry-otlp-exporter-node/0.45.0" \
          -d "$TRACE_PAYLOAD")
        
        echo "📊 HTTP Status: $HTTP_STATUS"
        if [ "$HTTP_STATUS" -eq 200 ] || [ "$HTTP_STATUS" -eq 202 ] || [ "$HTTP_STATUS" -eq 204 ]; then
          echo "✅ Trace sent successfully via JSON OTLP endpoint"
          rm -f /tmp/trace_response*.txt
          exit 0
        else
          echo "⚠️ JSON OTLP endpoint failed:"
          cat /tmp/trace_response1.txt 2>/dev/null || echo "No response body"
        fi
        
        # Method 2: Try with explicit JSON content type and OTLP path
        ALT_ENDPOINT="${TRACE_ENDPOINT%/*}/traces"
        if [ "$ALT_ENDPOINT" != "$TRACE_ENDPOINT" ]; then
          echo "🔄 Method 2: Alternative traces endpoint: $ALT_ENDPOINT"
          HTTP_STATUS=$(curl -s -w "%{http_code}" -o /tmp/trace_response2.txt \
            -X POST "$ALT_ENDPOINT" \
            -H "Authorization: Api-Token $API_TOKEN" \
            -H "Content-Type: application/json" \
            -H "User-Agent: opentelemetry-otlp-exporter-node/0.45.0" \
            -d "$TRACE_PAYLOAD")
          
          echo "📊 HTTP Status: $HTTP_STATUS"
          if [ "$HTTP_STATUS" -eq 200 ] || [ "$HTTP_STATUS" -eq 202 ] || [ "$HTTP_STATUS" -eq 204 ]; then
            echo "✅ Trace sent successfully via alternative endpoint"
            rm -f /tmp/trace_response*.txt
            exit 0
          else
            echo "⚠️ Alternative endpoint failed:"
            cat /tmp/trace_response2.txt 2>/dev/null || echo "No response body"
          fi
        fi
        
        # Method 3: Log the issue and skip traces to prevent blocking
        echo "❌ All trace sending methods failed, but continuing workflow..."
        echo "🔍 Debug info:"
        echo "   Endpoint: $TRACE_ENDPOINT"
        echo "   Payload size: $(echo "$TRACE_PAYLOAD" | wc -c) bytes"
        rm -f /tmp/trace_response*.txt
        exit 0  # Don't fail the workflow for trace issues
        EOF
        
        sudo chmod +x /usr/local/bin/send-trace
        echo "✅ Trace utilities installed"

    - name: Initialize trace and logging
      id: init-trace
      shell: bash
      run: |
        # Debug input parameters
        echo "🔍 Input parameters:"
        echo "  otel-endpoint: ${{ inputs.otel-endpoint }}"
        echo "  dynatrace-log-url: ${{ inputs.dynatrace-log-url }}"
        echo "  dynatrace-api-token: ${DYNATRACE_API_TOKEN:+SET}"
        
        # Validate required inputs
        if [ -z "${{ inputs.otel-endpoint }}" ] || [ "${{ inputs.otel-endpoint }}" = "https://your-tenant.live.dynatrace.com/api/v2/otlp/v1/traces" ]; then
          echo "❌ OTEL endpoint not properly configured!"
          echo "Please set OTEL_EXPORTER_OTLP_ENDPOINT in your environment variables"
          exit 1
        fi
        
        if [ -z "${{ inputs.dynatrace-api-token }}" ]; then
          echo "❌ Dynatrace API token not provided!"
          echo "Please set DYNATRACE_API_TOKEN in your environment secrets"
          exit 1
        fi
        
        # Generate a unique trace ID for this job
        TRACE_ID=$(openssl rand -hex 16)
        echo "trace-id=$TRACE_ID" >> $GITHUB_OUTPUT
        
        # Determine build type based on branch
        BUILD_TYPE="prod"
        case "${{ github.ref }}" in
          "refs/heads/dev")
            BUILD_TYPE="dev"
            ;;
          "refs/heads/main"|"refs/heads/master")
            BUILD_TYPE="prod"
            ;;
          *)
            # For PRs, check the base branch
            case "${{ github.base_ref }}" in
              "dev")
                BUILD_TYPE="dev"
                ;;
              "main"|"master")
                BUILD_TYPE="prod"
                ;;
            esac
            ;;
        esac
        
        echo "build-type=$BUILD_TYPE" >> $GITHUB_OUTPUT
        
        # Set up OTel environment variables using exact .env names
        OTEL_ENDPOINT="${{ inputs.otel-endpoint }}"
        echo "otel-endpoint=$OTEL_ENDPOINT" >> $GITHUB_OUTPUT
        
        # Export environment variables for subsequent steps (matching .env file names)
        echo "OTEL_EXPORTER_OTLP_ENDPOINT=$OTEL_ENDPOINT" >> $GITHUB_ENV
        echo "OTEL_EXPORTER_OTLP_HEADERS=Authorization=Api-Token ${{ inputs.dynatrace-api-token }}" >> $GITHUB_ENV
        echo "OTEL_SERVICE_NAME=dynatrace-mcp-server-build" >> $GITHUB_ENV
        echo "DYNATRACE_API_TOKEN=${{ inputs.dynatrace-api-token }}" >> $GITHUB_ENV
        echo "DYNATRACE_LOG_INGEST_URL=${{ inputs.dynatrace-log-url }}" >> $GITHUB_ENV
        echo "OTEL_RESOURCE_ATTRIBUTES=github.workflow=${{ github.workflow }},github.job=${{ inputs.job-name }},github.run_id=${{ github.run_id }},github.actor=${{ github.actor }},build.type=$BUILD_TYPE,branch.name=${{ github.ref_name }},branch.ref=${{ github.ref }}" >> $GITHUB_ENV
        echo "GITHUB_TRACE_ID=$TRACE_ID" >> $GITHUB_ENV
        echo "BUILD_TYPE=$BUILD_TYPE" >> $GITHUB_ENV
        
        echo "🔧 OTel initialized with trace ID: $TRACE_ID"
        echo "📡 Endpoint: $OTEL_ENDPOINT"
        echo "📝 Log URL: ${{ inputs.dynatrace-log-url }}"
        echo "🏗️ Build type: $BUILD_TYPE"
        echo "🌿 Branch: ${{ github.ref_name }}"
        
        # Test connectivity to Dynatrace OTLP endpoint with proper format
        echo "🧪 Testing Dynatrace OTLP connectivity..."
        
        CURRENT_TIME_NS=$(($(date +%s) * 1000000000))
        TEST_SPAN_ID=$(openssl rand -hex 8)
        
        # Use proper OTLP v1.0.0 JSON format matching the working otel.ts
        TEST_TRACE_PAYLOAD=$(cat << EOF
        {
          "resourceSpans": [
            {
              "resource": {
                "attributes": [
                  {
                    "key": "service.name",
                    "value": {
                      "stringValue": "dynatrace-mcp-server-build"
                    }
                  },
                  {
                    "key": "service.version", 
                    "value": {
                      "stringValue": "github-actions"
                    }
                  },
                  {
                    "key": "telemetry.sdk.name",
                    "value": {
                      "stringValue": "opentelemetry"
                    }
                  },
                  {
                    "key": "telemetry.sdk.language",
                    "value": {
                      "stringValue": "shell"
                    }
                  },
                  {
                    "key": "telemetry.sdk.version",
                    "value": {
                      "stringValue": "1.0.0"
                    }
                  }
                ]
              },
              "scopeSpans": [
                {
                  "scope": {
                    "name": "github-actions-otel",
                    "version": "1.0.0"
                  },
                  "spans": [
                    {
                      "traceId": "$TRACE_ID",
                      "spanId": "$TEST_SPAN_ID",
                      "name": "github.connectivity.test",
                      "kind": 1,
                      "startTimeUnixNano": "$CURRENT_TIME_NS",
                      "endTimeUnixNano": "$((CURRENT_TIME_NS + 1000000000))",
                      "status": {
                        "code": 1
                      },
                      "attributes": [
                        {
                          "key": "test.type",
                          "value": {
                            "stringValue": "connectivity"
                          }
                        },
                        {
                          "key": "build.type",
                          "value": {
                            "stringValue": "$BUILD_TYPE"
                          }
                        },
                        {
                          "key": "github.workflow",
                          "value": {
                            "stringValue": "${{ github.workflow }}"
                          }
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
        EOF
        )
        
        # Send test trace and capture result
        if send-trace "$OTEL_ENDPOINT" "${{ inputs.dynatrace-api-token }}" "$TEST_TRACE_PAYLOAD"; then
          echo "✅ Trace connectivity test successful"
        else
          echo "⚠️ Trace connectivity test failed, but continuing..."
        fi
        
        # Send initial job start log to Dynatrace (this is working)
        if [ -n "${{ inputs.dynatrace-log-url }}" ] && [ -n "${{ inputs.dynatrace-api-token }}" ]; then
          JOB_START_LOG="Starting GitHub Actions job: ${{ inputs.job-name }} for workflow ${{ github.workflow }} with trace ID: $TRACE_ID"
          LOG_TIMESTAMP=$(date +%s%3N)
          
          JOB_LOG_PAYLOAD=$(cat << EOF
          [{
            "content": "$JOB_START_LOG",
            "timestamp": $LOG_TIMESTAMP,
            "level": "INFO",
            "service": "dynatrace-mcp-server-build",
            "trace_id": "$TRACE_ID",
            "span_id": "$TEST_SPAN_ID",
            "github.workflow": "${{ github.workflow }}",
            "github.job": "${{ inputs.job-name }}",
            "github.run_id": "${{ github.run_id }}",
            "github.actor": "${{ github.actor }}",
            "github.ref": "${{ github.ref }}",
            "build.type": "$BUILD_TYPE",
            "branch.name": "${{ github.ref_name }}",
            "ci.provider": "github-actions",
            "project.name": "dynatrace-mcp-server",
            "log.type": "job.start"
          }]
        EOF
          )
          
          LOG_STATUS=$(curl -s -w "%{http_code}" -o /tmp/log_response.txt \
            -X POST "${{ inputs.dynatrace-log-url }}" \
            -H "Authorization: Api-Token ${{ inputs.dynatrace-api-token }}" \
            -H "Content-Type: application/json" \
            -d "$JOB_LOG_PAYLOAD")
          
          if [ "$LOG_STATUS" -eq 200 ] || [ "$LOG_STATUS" -eq 204 ]; then
            echo "📝 Job start logged to Dynatrace successfully"
          else
            echo "⚠️ Job start log failed (HTTP $LOG_STATUS):"
            cat /tmp/log_response.txt 2>/dev/null || echo "No response"
          fi
          rm -f /tmp/log_response.txt
        fi

    - name: Start job trace
      shell: bash
      run: |
        echo "🚀 Starting job trace for ${{ inputs.job-name }} (build type: $BUILD_TYPE)"
        
        CURRENT_TIME_NS=$(($(date +%s) * 1000000000))
        JOB_SPAN_ID=$(openssl rand -hex 8)
        
        # Use proper OTLP v1.0.0 format for job span
        JOB_TRACE_PAYLOAD=$(cat << EOF
        {
          "resourceSpans": [
            {
              "resource": {
                "attributes": [
                  {
                    "key": "service.name",
                    "value": {
                      "stringValue": "dynatrace-mcp-server-build"
                    }
                  },
                  {
                    "key": "telemetry.sdk.name",
                    "value": {
                      "stringValue": "opentelemetry"
                    }
                  },
                  {
                    "key": "telemetry.sdk.language",
                    "value": {
                      "stringValue": "shell"
                    }
                  }
                ]
              },
              "scopeSpans": [
                {
                  "scope": {
                    "name": "github-actions-otel",
                    "version": "1.0.0"
                  },
                  "spans": [
                    {
                      "traceId": "$GITHUB_TRACE_ID",
                      "spanId": "$JOB_SPAN_ID",
                      "name": "github.job.${{ inputs.job-name }}",
                      "kind": 1,
                      "startTimeUnixNano": "$CURRENT_TIME_NS",
                      "status": {
                        "code": 1
                      },
                      "attributes": [
                        {
                          "key": "job.name",
                          "value": {
                            "stringValue": "${{ inputs.job-name }}"
                          }
                        },
                        {
                          "key": "github.actor",
                          "value": {
                            "stringValue": "${{ github.actor }}"
                          }
                        },
                        {
                          "key": "build.type",
                          "value": {
                            "stringValue": "$BUILD_TYPE"
                          }
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
        EOF
        )
        
        # Send job trace
        if send-trace "$OTEL_EXPORTER_OTLP_ENDPOINT" "$DYNATRACE_API_TOKEN" "$JOB_TRACE_PAYLOAD"; then
          echo "✅ Job trace sent successfully"
        else
          echo "⚠️ Job trace sending failed"
        fi
        
        # Store job span info for later completion
        echo "GITHUB_JOB_SPAN_ID=$JOB_SPAN_ID" >> $GITHUB_ENV
        echo "GITHUB_JOB_START_TIME_NS=$CURRENT_TIME_NS" >> $GITHUB_ENV